### ISSUE TITLE
foreachInit not working...

### ISSUE THREAD

**Issue by DanielStaroscik** [ErikSchierboom/knockout-pre-rendered#60]
Hi i'm trying to using foreachInit in ASP.NET Core 3.1 app:

[view.txt](https://github.com/ErikSchierboom/knockout-pre-rendered/files/4124543/view.txt)

And its my view-model (in typescript):
`export class InvoiceViewModel extends BaseViewModel {
    private date: KnockoutComputed<Dayjs>;
    private dateOfService: KnockoutComputed<Dayjs>;

    constructor() {
        super();

        this.date = ko.computed<Dayjs>(() => Dayjs(this.Date(), "DD.MM.YYYY"));
        this.dateOfService = ko.computed<Dayjs>(() => Dayjs(this.DateOfService(), "DD.MM.YYYY"));
    }

    public Id = ko.observable<string>();

    public OurInstitutionId = ko.observable<string>();

    public Number = ko.observable<string>();

    public Date = ko.observable<string>();

    public DateOfService = ko.observable<string>();

    public Seller = new SellerViewModel();

    public Buyer = new BuyerViewModel();

    public IsReceivierApplied = ko.observable<boolean>();

    public Receivier = new ReceivierViewModel();

    public Items = ko.observableArray<InvoiceItemViewModel>();

    public Caution = ko.observable<string>();

    public Footnote = ko.observable<string>();

    public IsSended = ko.observable<boolean>();

    public IsPaid = ko.observable<boolean>();

    public AddItem() { }

    public SearchByNip() { }

    public Cancel() {
        super.Cancel("/BusinessManager/Invoices");
    }
}`

From my .net core app i have rendered one child in div witch data-bind "foreachInit"
but when i chceck it in browser console `viewModel.Items() it is empty...

**Comment by jlunman** [comment]
Since your `Items()` array starts out empty, you need to tell the `foreachInit` binding how to create new array elements for each pre-rendered HTML element it finds.

So your ViewModel needs a method that creates an instance of the model for each item:

```
public createItem() {
    return {
        Id: ko.observable(),
        InvoiceId: ko.observable(),
        Title: ko.observable(),
        Unit: ko.observable(),
        ... etc...
    };
}
```
Or, if you already have a model class for these items, your `createItem` method can just do:
```
public createItem() {
    return new InvoiceItemViewModel();
}
```

And then you reference this method as the `createElement` parameter of the `foreachInit` binding,

```
data-bind="foreachInit: { data: Items, name: 'itemTemplate', createElement: createItem }"
```

See also this example: https://github.com/ErikSchierboom/knockout-pre-rendered/blob/master/examples/foreach-init-using-create-element.html

**Comment by ErikSchierboom** [comment]
@DanielStaroscik Does the above suggestion solve your issue? Thanks for answering @jlunman BTW!

**Comment by DanielStaroscik** [comment]
@ErikSchierboom Yes, it works perfect :)
